fix build error on alpin due to missing header
realm/util/cli_args.cpp:69:1: error: 'int64_t' does not name a type
69 | int64_t CliArgument::as<int64_t>() const